modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/BackTools/issues"

[[mods]]
    modId="backtools"
    version="${file.jarVersion}" #mandatory
    displayName="Back Tools"
    displayURL="https://ichun.me/mods/back-tools/"
    authors="iChun"
    description='''
    Shows the last used tool on the player's back. Purely aesthetic.
    '''

[[dependencies.backtools]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
